### ISSUE TITLE
开启cc依旧不能展示字幕

### ISSUE THREAD

**Issue by markcheney1** [ADengrc/youtube-captions#10]
从master上拉了代码，依旧不能使用，开启了cc字幕就不能显示了

**Comment by markcheney1** [comment]
xhr的response返回已经变成了xml，不是json格式了
![image](https://user-images.githubusercontent.com/20323958/73606766-ab7c4a00-45e8-11ea-8ec0-1fd716ab3d8c.png)

**Comment by cccvvv2012** [comment]
可以使用 Dualsub插件，实际效果更好，自定义的选项更多

**Comment by markcheney1** [comment]
> 可以使用 Dualsub插件，实际效果更好，自定义的选项更多

可以用

**Comment by markcheney1** [comment]
不过作者也要加油呀💪

**Comment by ADengrc** [comment]
又变回json了
