### ISSUE TITLE
有多个字幕的视频 只能用中文字幕

### ISSUE THREAD

**Issue by xidadan** [ADengrc/youtube-captions#11]
https://www.youtube.com/watch?v=spUNpyF58BY&t=12s
你好，这个视频里边的字幕，在开启插件的情况下，只有选择中文字幕，才会出现字幕，选择其他的语言就没有字幕了，希望可以解决下这个问题。win10 edge81

**Comment by ADengrc** [comment]
已经修复了，可以克隆代码使用，线上版本审核通过后会发布。
