### ISSUE TITLE
请教一下如何修改代码可以将中文放到英文下面显示？

### ISSUE THREAD

**Issue by nb5p** [ADengrc/youtube-captions#14]
软件很不错，非常的方便。就是中文在上这种形式看着不太习惯，之前看双语字幕习惯了英文在上的形式。请我该在本地问如何修改，才可以调换位置。

**Comment by ADengrc** [comment]
https://github.com/ADengrc/youtube-captions/commit/a00c3d8f6f1a02120a660c1d59c66dcafea26eea#diff-9487b1592e288e27483ba7c612113a1a
可以看上面的更改记录哈
