### ISSUE TITLE
有中文简体或繁体字幕的视频会只显示英文字幕

### ISSUE THREAD

**Issue by donglisi** [ADengrc/youtube-captions#15]
例如：
https://www.youtube.com/watch?v=OsbV1_tA1oU
https://www.youtube.com/watch?v=VHMYl70ibHQ

**Comment by donglisi** [comment]
删除这四行代码可以和没有中文字幕的视频一样使用机器翻译：

https://github.com/kgdboc/youtube-captions/commit/9fe85efe333a1124249f8668d41e4e93ad51a6c2

**Comment by ADengrc** [comment]
这两个是因为两种字幕时间戳不一致导致无法合并，可以克隆后自行修改哈
