### ISSUE TITLE
你好 能不能让双字幕一直是开启状态

### ISSUE THREAD

**Issue by ilovebamboo** [ADengrc/youtube-captions#4]
RT 非常感谢

**Comment by ADengrc** [comment]
目前插件安装完就是默认一直开启的，所以不是很理解你说的问题，可以再具体描述一下吗？

**Comment by ilovebamboo** [comment]
我在观看视频的时候 每次需要点击字幕才能看开启
![image](https://user-images.githubusercontent.com/6214084/59836099-869ad580-937d-11e9-8fcf-35dd7709bb8b.png)
![image](https://user-images.githubusercontent.com/6214084/59836137-961a1e80-937d-11e9-9418-877d9a1341ee.png)
我需要点击这个才能看到字幕 我的意思是，不需要点击就可以，
我没找到哪里可以自动设置，谢谢请多多指教。

**Comment by ilovebamboo** [comment]
每一节视频都需要点击一次。请问有没有办法不点就可以，我在WIN平台也是同样问题。
https://www.youtube.com/watch?v=wiozYyXQEVk

**Comment by ADengrc** [comment]
你可以尝试下点右上角的头像，然后点设置，然后点击播放和效果，把里面的勾都勾上再点保存试试

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/59970110-12388000-9591-11e9-8854-4e9de2e15325.png)
已经勾选好了

**Comment by ilovebamboo** [comment]
已经解决了 谢谢您
