### ISSUE TITLE
请求考虑繁体字幕而非机翻

### ISSUE THREAD

**Issue by shuwai** [ADengrc/youtube-captions#5]
考虑都某些视频有繁体无简体，当有繁体字幕存在，应当调用繁体而非机翻简体

**Comment by ADengrc** [comment]
有具体视频链接吗？

**Comment by shuwai** [comment]
感谢回复！
1. 这个频道大部分视频都有繁体翻译，您可以参考一下。
https://www.youtube.com/watch?v=du8siPJ1ZKo

2. 另外，似乎在有简体的情况下，还是会调用机翻，我的插件版本是1.2。如下图
https://www.youtube.com/watch?v=StW7oGSR_Mg
![image](https://user-images.githubusercontent.com/42209556/61059327-682f7380-a42b-11e9-92f4-44206bfa5859.png)

**Comment by shuwai** [comment]
感谢回复！

这个频道大部分视频都有繁体翻译，您可以参考一下。
https://www.youtube.com/watch?v=du8siPJ1ZKo

**Comment by ADengrc** [comment]
这个不是机翻哈，不过调用的是台湾的字幕
