### ISSUE TITLE
突然就用不了了，英文中文都没有

### ISSUE THREAD

**Issue by ratafee1** [ADengrc/youtube-captions#9]
![image](https://user-images.githubusercontent.com/31762195/72930050-0cf51b00-3d96-11ea-8762-7c615e19b573.png)

**Comment by halu1999** [comment]
![微信截图_20200123102321](https://user-images.githubusercontent.com/47176470/72951730-6a0ac400-3dca-11ea-9a4c-a28ef8cb7070.png)
我的也是，好像是XMLHttpRequest已被弃用。
